### ISSUE TITLE
登录时，输入小区名称后无法继续往下执行，返回KeyError: 'geocodes'

### ISSUE THREAD

**Issue by wossQ** [gerenyongcangku/imaotai#3]
root@Others:/ql/data/scripts/gerenyongcangku_imaotai $ python login.py

请输入你的位置，例如[小区名称]，为你自动预约附近的门店:碧桂园
Traceback (most recent call last):
  File "/ql/data/scripts/gerenyongcangku_imaotai/login.py", line 55, in <module>
    location_select: dict = get_location()
                            ^^^^^^^^^^^^^^
  File "/ql/data/scripts/gerenyongcangku_imaotai/login.py", line 33, in get_location
    selects = process.select_geo(location)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/gerenyongcangku_imaotai/process.py", line 261, in select_geo
    geocodes: list = resp.json()['geocodes']
                     ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'geocodes'

**Comment by ly90907** [comment]
应该是作者调用的api的key用光了

我申请了高德的key，但是不知道怎么结合api使用，没有找到教程

**Comment by ly90907** [comment]
研究了一下搞定了
process.py 的260改成
    resp = requests.get(f"https://restapi.amap.com/v3/geocode/geo?address={i}&key=xxxxxxxx")
key中的xxxxxxx改成你自己申请的高德api的key，教程参考https://lbs.amap.com/api/webservice/create-project-and-key

**Comment by wossQ** [comment]
> 应该是作者调用的api的key用光了
> 
> 我申请了高德的key，但是不知道怎么结合api使用，没有找到教程

emmm，我直接临时解决，将获取地理位置的注释掉了，登录了再手动去完善地址信息就好了

**Comment by jia-heart-rabbit** [comment]
> 研究了一下搞定了 process.py 的260改成 resp = requests.get(f"[https://restapi.amap.com/v3/geocode/geo?address={i}&key=xxxxxxxx](https://restapi.amap.com/v3/geocode/geo?address=%7Bi%7D&key=xxxxxxxx)") key中的xxxxxxx改成你自己申请的高德api的key，教程参考https://lbs.amap.com/api/webservice/create-project-and-key

我按照您说的做，还是报错呀

**Comment by jia-heart-rabbit** [comment]
> > 应该是作者调用的api的key用光了
> > 我申请了高德的key，但是不知道怎么结合api使用，没有找到教程
> 
> emmm，我直接临时解决，将获取地理位置的注释掉了，登录了再手动去完善地址信息就好了

是注释掉login.py里面的吗
